### ISSUE TITLE
Assets license

### ISSUE THREAD

**Issue by ghost** [17cupsofcoffee/Still-Hungry#26]
It is only told about _source_ license. Let me try… The assets license (textures, sounds, models, etc.) is Creative Commons 3. Am I right?

**Comment by 17cupsofcoffee** [comment]
I haven't actually given any thought to this until now, so thanks for bringing this to our attention. The open source licencing doesn't cover the art, the rights to that belong to DizzyAlyx, who made it all. We might consider more permissive licenses in the future, but for the foreseeable future, the assets are all copyrighted to her and are not free to use. I'll update the README.md to reflect this, as it's not clear at the minute!

**Comment by ghost** [comment]
Then, 2 questions:
1. Can assets be uploaded to [Minecraft Wiki](http://minecraft.gamepedia.com), Asassin 1 is going to write articles about the mod?
2. If yes, then, should I choose [Copyright license](http://minecraft.gamepedia.com/Template:License_copyright) to the uploaded files?

**Comment by 17cupsofcoffee** [comment]
I think you'd be able to upload them under fair use terms whether we said so or not, but just to be sure I'll give explicit permission here:

**For purposes of information or documentation, such as use on the Minecraft Wiki or anything similar, we give our permission for the copyrighted assets from Still Hungry to be copied/used.**

If you upload the files using the copyright license and give a link to this comment in the summary as proof permission has been given, I think that ought to be sufficient!
