### ISSUE TITLE
Still hungry mod -- oven bugs

### ISSUE THREAD

**Issue by NickKenobi1112** [17cupsofcoffee/Still-Hungry#3]
I'm unable to shift-click with the oven, and the oven doesn't recognize blocks of coal as fuel like it should.

**Comment by 17cupsofcoffee** [comment]
The shift clicking was a known issue - never got around to implementing it! Completely forgot they added coal blocks in 1.6 though, will have to add that.

**Comment by 17cupsofcoffee** [comment]
Coal blocks are added to the stove, there's a pretty annoying duping bug when I tried to add shift click functionality to it though - going to hold off on that until next version, don't want to rush it out until I know it works
