### ISSUE TITLE
Buckets are duplicating

### ISSUE THREAD

**Issue by flaqu123** [17cupsofcoffee/Still-Hungry#7]
Hi, when i take milk from cow, and i go to furnance to make cheese from it, it gives me 2 empty buckets. Please, fix this bug (1.6.2)

**Comment by 17cupsofcoffee** [comment]
Should be fixed in the upcoming version, sorry for the wait!

**Comment by 17cupsofcoffee** [comment]
Well it wasn't fixed actually...

**Comment by 17cupsofcoffee** [comment]
BUT NOW IT IS
