### ISSUE TITLE
Right clicking lunchbox crashes the game

### ISSUE THREAD

**Issue by rufimeru** [17cupsofcoffee/Still-Hungry#8]
when i right click on it it crashes the game :I i cant open it  ( update 1.7.2 )

**Comment by 17cupsofcoffee** [comment]
Yep, this problem is happening on my end too :/ My fault for not bugtesting enough. There'll be a hotfix out in the next day or two, gonna get straight to work on this!

**Comment by ghost** [comment]
Any fix please ? Still crashing.. :/

**Comment by 17cupsofcoffee** [comment]
Sorry, I know it's been far too long :( College deadlines kinda sapped me of the will to work on the mod for a while, I'm gonna work on it this weekend though. Rest assured we will definitely fix it.

**Comment by 17cupsofcoffee** [comment]
FINALLY. Fix coming in tonight's update.
