### ISSUE TITLE
Creative tab for mod items and blocks

### ISSUE THREAD

**Issue by labpaw** [17cupsofcoffee/Still-Hungry#9]
Title says it all.

**Comment by 17cupsofcoffee** [comment]
Hmm, I'm not sure if this is necessary, all the items fit pretty well into the existing categories in vanilla creative? I'll consider adding it though.

**Comment by labpaw** [comment]
Food plus, Usefulfood and Lots of Food(Food mods) have their own creative tabs. Why not to make creative tab for your mod too?

**Comment by 17cupsofcoffee** [comment]
Well if it's something ALL the other mods have done I guess it doesn't make a lot of sense for us not to. Will try to get it in for the next version!

**Comment by 17cupsofcoffee** [comment]
Done!
